[package]
name = "rust_sprite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
serde_derive = "1.0.130"